import { createTheme } from '@fluentui/react';

export const dark = createTheme({
  palette: {
    themePrimary: '#80c1f2',
    themeLighterAlt: '#fafcfe',
    themeLighter: '#eaf5fd',
    themeLight: '#d8ecfb',
    themeTertiary: '#b2d9f7',
    themeSecondary: '#8fc8f4',
    themeDarkAlt: '#74aeda',
    themeDark: '#6293b8',
    themeDarker: '#486c88',
    neutralLighterAlt: '#343434',
    neutralLighter: '#3d3d3d',
    neutralLight: '#4a4a4a',
    neutralQuaternaryAlt: '#525252',
    neutralQuaternary: '#595959',
    neutralTertiaryAlt: '#757575',
    neutralTertiary: '#c8c8c8',
    neutralSecondary: '#d0d0d0',
    neutralPrimaryAlt: '#dadada',
    neutralPrimary: '#ffffff',
    neutralDark: '#f4f4f4',
    black: '#f8f8f8',
    white: '#2b2b2b',
  },
});

export const light = createTheme({
  palette: {
    themePrimary: '#31a9c4',
    themeLighterAlt: '#f5fbfd',
    themeLighter: '#d8f0f6',
    themeLight: '#b8e4ed',
    themeTertiary: '#79cadc',
    themeSecondary: '#45b3cb',
    themeDarkAlt: '#2c98b1',
    themeDark: '#258195',
    themeDarker: '#1b5f6e',
    neutralLighterAlt: '#f8f8f8',
    neutralLighter: '#f4f4f4',
    neutralLight: '#eaeaea',
    neutralQuaternaryAlt: '#dadada',
    neutralQuaternary: '#d0d0d0',
    neutralTertiaryAlt: '#c8c8c8',
    neutralTertiary: '#b7b7b7',
    neutralSecondary: '#a0a0a0',
    neutralPrimaryAlt: '#888888',
    neutralPrimary: '#2b2b2b',
    neutralDark: '#5a5a5a',
    black: '#434343',
    white: '#ffffff',
  },
});
